[tool.black]
exclude = ['migrations', 'venv']

[tool.isort]
profile = 'black'
known_django = 'django'
sections = 'FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
skip = ['migrations', 'venv']
