# Generated by Django 4.1.3 on 2022-12-12 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_public",
                    models.BooleanField(default=True, verbose_name="資料公開"),
                ),
                (
                    "schedule_public",
                    models.BooleanField(default=True, verbose_name="スケジュール公開"),
                ),
                (
                    "insert_page",
                    models.BooleanField(default=True, verbose_name="ページ数の表示"),
                ),
                (
                    "time_keeper",
                    models.BooleanField(default=True, verbose_name="定期タイムキーパー"),
                ),
                (
                    "time_keeper_interval",
                    models.IntegerField(default=1, verbose_name="定期通知間隔"),
                ),
                (
                    "finish_keeper",
                    models.BooleanField(default=True, verbose_name="終了前タイムキーパー"),
                ),
                (
                    "finish_keeper_start",
                    models.IntegerField(default=30, verbose_name="終了前通知スタート時間"),
                ),
                (
                    "finish_keeper_interval",
                    models.IntegerField(default=10, verbose_name="終了前通知間隔"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "個人設定",
            },
        ),
        migrations.CreateModel(
            name="MyselfPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insert_name",
                    models.CharField(
                        choices=[
                            ("full_name", "本名"),
                            ("view_name", "表示名"),
                            ("username", "ユーザー名"),
                        ],
                        default="full_name",
                        max_length=9,
                        verbose_name="記載する名前",
                    ),
                ),
                (
                    "insert_icon",
                    models.BooleanField(default=True, verbose_name="アイコンを表示"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/myself", verbose_name="自己紹介ファイル"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "自己紹介ページ",
            },
        ),
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="タイトル")),
                (
                    "file",
                    models.FileField(upload_to="documents/%Y/%m/%d", verbose_name="資料"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "作成した資料",
            },
        ),
    ]
